### ISSUE TITLE
Adding an OFL-licensed Ol Chiki (for Santali language) font

### ISSUE THREAD

**Issue by psubhashish** [pgajdos/fontinfo#1]
Hi, can you please add the Ol Chiki font [Guru Gomke](https://github.com/GuruGomke/files) — which is an OFL-licensed font that is also bundled with open source [input tools](https://github.com/GuruGomke/files/tree/master/Input-tools) to the Suse project directory? Would really appreciate if you can help with this. Thanks in advance!

**Comment by pgajdos** [comment]
Hey,

your request is completely unrelated to fontinfo package, so I will close. 

You have two issues:
(1) package fonts
(2) package 'input tool'

While (1) is no problem for me (I have already did in https://build.opensuse.org/request/show/510949), I have no idea what should be done for (2). To resolve (2), you can try to contact opensuse-m17n@ mailing list (https://lists.opensuse.org/opensuse-m17n/) or opensuse-factory@ mailing list (https://lists.opensuse.org/opensuse-factory/), I would propose in that order.
